### ISSUE TITLE
Compatibility issue with Python 3.7

### ISSUE THREAD

**Issue by AiOO** [nirum-lang/nirum-python#116]
Since the `typing` module in Python 3.7 doesn't have `TupleMeta` class, `AttributeError` occurs by below line . To support Python 3.7 it should be fixed.

https://github.com/nirum-lang/nirum-python/blob/1721295424fdc07368c376cf9a3ead6f4b7bffe6/nirum/deserialize.py#L203

relative commit: https://github.com/python/cpython/commit/d911e40e788fb679723d78b6ea11cabf46caed5a#diff-015978a768b517a38abbc0ecdea87f5a

**Comment by kanghyojun** [comment]
However, with the higher version of Nirum compiler, `deserialize_meta` dosen't used anymore. So we should fix compiler code https://github.com/nirum-lang/nirum/blob/0.5-maintenance/src/Nirum/Targets/Python.hs

**Comment by kanghyojun** [comment]
`deserialized_meta` was deprecated, Since https://github.com/nirum-lang/nirum/pull/278 was merged. So I think that there are no bugs if you use the latest version of Nirum compiler. Thanks for your reporting :)
